SELECT b.`KEY`,COUNT(m.`KEY`) AS cntM, b.* FROM BONOS_MANTENIMIENTO b INNER JOIN MANTENIMIENTO m ON m.BONOASOCIADO_KEY_OID=b.`KEY` GROUP BY b.`KEY` HAVING cntM>1;


-- Consiliar si este listado corresponde con el listado se sesiones realizadas de un bono.
SELECT b.`KEY`, b.CLIENTEASOCIADO_KEY_OID, b.NOMBRECLIENTE, b.FECHACONTRATACION, b.FECHAINICIO, b.OPERADORASOCIADO_KEY_OID,b.NOMBREOPERADOR,b.SECUENCIALBONO,b.TIPO, b.OBSERVACIONES, m.FECHAMANTENIMIENTO,m.OBSERVACIONES,m.ESTADOMANTENIMIENTO_KEY_OID,m.HORAINICIO,m.HORAFIN,m.OPERADORASOCIADO_KEY_OID FROM BONOS_MANTENIMIENTO b INNER JOIN MANTENIMIENTO m ON m.BONOASOCIADO_KEY_OID=b.`KEY`;


-- SELECT * FROM REVISION r WHERE r.FECHAREVISION>CURDATE()
SELECT 
		`KEY` AS __MigDiaryGID,
		CENTROASOCIADO_KEY_OID AS DiaryGClinicID,
		CLIENTEASOCIADO_KEY_OID AS DiaryGClientID,
		CONCAT(
			'Código de tratamiento: ', IFNULL(CODIGOTRATAMIENTO,' - '),'\n',	
			'Secuencial de tratamiento :', IFNULL(SECUENCIALTTO,' - '),'\n',			
			'Operador: ',IFNULL(OPERADOR,' - '),'\n',
			'Hora prevista: ',IFNULL(TIME(HORAPREVISTA),' - '),'\n',
			'Fecha tratamiento: ',IFNULL(DATE_FORMAT(FECHATRATAMIENTO,'%d/%m/%Y'),' - '),'\n',
			'Tipo: ',IFNULL(TIPO,' - '),'\n',
			'Observaciones: ',IFNULL(OBSERVACIONES,' - '),'\n',
			'Estado: ',IFNULL(NOMBREESTADO,' - '),'\n',
			'Revisión externa: ',if(REVISIONEXTERNA=0,'No','Si'),'\n',
			'Observaciones de revisión externa: ',IFNULL(OBSERVACIONESREVISIONEXTERNA,' - '),'\n'			
			) AS DiaryGComments,
		FECHAREVISION AS DiaryGDate,	
		SEC_TO_TIME(ROUND(TIME_TO_SEC(TIME(HORAINICIO)) / 60 / 15) * 15 * 60) AS DiaryGStart,
		SEC_TO_TIME(ROUND(TIME_TO_SEC(TIME(HORAFIN)) / 60 / 15) * 15 * 60) AS DiaryGEnd,
		1 AS DiaryGCabinetNum,
		0 AS DiaryGUserID, 
		CURDATE() AS  DiaryGCreated,
		-1 AS DiaryGMigrated,
		t.OPERADORASOCIADO_KEY_OID
		
 FROM TRATAMIENTO t 
 WHERE t.FECHAREVISION>CURDATE();


-- Usuarios
SELECT DISTINCT U.`KEY` AS UserID, U.NOMBRE AS UserName, CONCAT( PERFIL, '-',O.CENTROASOCIADO_KEY_OID) AS  UserNotes, U.USUARIOGOOGLE AS UserLogin,  U.USUARIOGOOGLE AS UserEMail, O.FECHAALTA AS UserDateNew, O.CENTROASOCIADO_KEY_OID , 201 UserCountryID FROM USUARIO U INNER JOIN  OPERADORDEFRANQUICIA O ON O.USUARIOASOCIADO_KEY_OID=U.`KEY` INNER JOIN TRATAMIENTO T ON T.OPERADORASOCIADO_KEY_OID=O.`KEY` WHERE T.FECHAREVISION>CURDATE() AND ISNULL(FECHABAJA);


